import Head from 'next/head'

type HeaderProps = {
    title?: string
}


const NormalHeader = ({ title = 'Finstable' }: HeaderProps) => {
    return (
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/finicon.png" />
      </Head>
    )
}

export default NormalHeader